import type { Metadata } from "next";
import {Tapestry} from "next/font/google";
import "./globals.css";
import Provider from "./provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tapestry = Tapestry({ 
  weight: "400",
  subsets: ["latin"] 
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={tapestry.className}
      ><Provider>{children}</Provider>
      </body>
    </html>
  );
}
